server:
  port: 8686

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/geeklol
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      database: mysql

logging:
  level:
    root: info
    org.hibernate.SQL: debug

lol.app-key: RGAPI-ca7daa27-d182-41c8-a43f-9a117cd68928