
server:
  port: 8686

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/lol_search
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      database: mysql

logging:
  level:
    root: info
    org.hibernate.SQL: debug

lol.app-key: RGAPI-8fd9c9c2-e192-4a44-a11c-5464565b046e

jwt:
  secret: Gt9jGFwmCAjnUG64pitfmWSm8v/0c1uNjYvTWxCUWpY8jNbUmgfXWk9h4CaA6UFC7kQtbjF4iqNtX2hkRaAe4w==